





# Numpy Basic

## Array

In [1]:
import numpy as np
import pandas as pd

In [2]:
list = [3, 6, 7, 8]

In [3]:
list

[3, 6, 7, 8]

In [4]:
type(list)

list

In [5]:
array = np.array(list) #Here we convert simple list into numpy array

In [6]:
array

array([3, 6, 7, 8])

In [7]:
type(array)

numpy.ndarray

## 2 dimensional array

In [8]:
list = [[4, 6, 7],[4, 3, 6], [7,4, 7]]

In [9]:
list

[[4, 6, 7], [4, 3, 6], [7, 4, 7]]

In [10]:
array = np.array(list) #here we convert simple list into numpy array

In [11]:
array

array([[4, 6, 7],
       [4, 3, 6],
       [7, 4, 7]])

In [12]:
arr= np.array([[[4, 6, 4], #Three dimensional
       [6, 7, 7],
       [6, 8, 9]],
      
      [[4, 6, 7],
       [6, 8, 5],
       [4, 7, 3]]])
      

In [13]:
arr

array([[[4, 6, 4],
        [6, 7, 7],
        [6, 8, 9]],

       [[4, 6, 7],
        [6, 8, 5],
        [4, 7, 3]]])

In [14]:
arr.ndim #In this way we can check dimensional

3

In [ ]:
arr.size

## Here we make numpy array through simple python array same thing we can do with 2 dimensional array

## Same thing we can do with one dimensional array by simply giving one 

In [ ]:
np.zeros((5,4))  

In [ ]:
np.ones((3,2))

In [ ]:
rang = np.arange(3, 9)

In [ ]:
rang

In [ ]:
rang.reshape((2,3)) #Here we change the shape of array 

In [ ]:
np.eye(4)

In [ ]:
rang.max()

In [ ]:
rang.argmax()

In [ ]:
linspac = np.linspace(1,6,8)

In [ ]:
linspac

In [ ]:
len(linspac)

## Random Numberz

In [ ]:
np.random.rand(2,2)

In [ ]:
np.random.randint(3,67,(2,4)) #Here we give (2,4) an array row and column

In [ ]:
np.random.choice(7,5) #Here 7 is a highest number and all the numberz chosen randomly are less than 7 and 5 is the length of array

## Python Indexing and selction

In [ ]:
arr

In [ ]:
arr[0,1,1] #Finding 3*3 using indexes

In [ ]:
arr[1: 2 :2]

In [ ]:
array

In [ ]:
array[1][1] #in two dimensional

In [ ]:
array[:2] #Not included two

In [ ]:
array[2:]

In [ ]:
array[2:] = 5 #Give 3 column = 5

In [ ]:
array 

In [ ]:
array2 = array.copy() #Make a copy of the previous array

In [ ]:
array2 

In [ ]:
array1 = np.array([5, 4, 6, 7, 3, 2])

In [ ]:
array1

In [ ]:
arra = array1>4

In [ ]:
array1[arra]

## Random seed

In [ ]:
np.random.seed(8) #When we use seed function it generate random number but still same
array4 = np.random.randint(1,9,(5,5))

In [ ]:
array4

## Arithametic Mean

In [ ]:
arr

In [ ]:
array

In [ ]:
list

In [ ]:
list + array

In [ ]:
one = [4, 6, 8]

In [ ]:
array + one #add two numbers

In [ ]:
np.add(one, array)

In [ ]:
np.add(one, one)

In [ ]:
np.square(array)

In [ ]:
arr + one

In [ ]:
arr

In [ ]:
array

In [ ]:
arr + array #It add firstly 2d array wit first part of 3d 